disabled_rules:
  - colon
  - comma
  - control_statement
  - identifier_name
  - type_name
  - trailing_comma
  - multiple_closures_with_trailing_closure
  - opening_brace

opt_in_rules:
  - empty_count
  - sorted_imports
  - anyobject_protocol

excluded:
  - Carthage
  - Pods
  - vendor/bundle

force_cast: error

force_try:
  severity: error

type_body_length:
  - 300
  - 400

function_body_length:
  - 200
  - 300

file_length:
  - 500
  - 1000

line_length: 200

nesting:
  type_level: 3
